### ISSUE TITLE
RSS icon

### ISSUE THREAD

**Issue by UisgeBeatha436** [creativetimofficial/ct-now-ui-kit-pro#34]
# Prerequisites
UI-Kit Pro version 1.2.2

I noticed the in range of social buttuns the rss-button is missing. Is there a way to add this button in a way it has the way of accessing and styling as the other social buttons?

**Comment by dragosct10** [comment]
Hi, @UisgeBeatha436! Thank you for using our products. Please see this [link ](https://fontawesome.com/icons/rss?style=solid)to take this RSS icon. 

Regards,
Dragos

**Comment by UisgeBeatha436** [comment]
Hi Dragos,

Thanks for replying. Found the icon.

The way I use the other icons is:
`<a class="btn btn-icon btn-pinterest btn-round" href="#" target="_blank" rel="noopener"><i class="fab fa-pinterest"></i></a>`

and icons are aligned nicely using the pro-kit, however the rss-icon isn't. 

`<a class="btn btn-icon btn-rss btn-round" href="#" target="_blank" rel="noopener"><i class="fas fa-rss"></i></a>`

Is this something I have to solve in the css or is a mis-use of one of the tags inside the a-class or i-class?

Thanks in advance.

**Comment by dragosct10** [comment]
Hi, @UisgeBeatha436! Please, can you give us your link to the project to see exactly what is happening there? 

Regards, 
Dragos

**Comment by UisgeBeatha436** [comment]
Hi,
I’d like to, however it’s on a local machine. Is there an email address I can send it to?
BR

**Comment by dragosct10** [comment]
Hi, @UisgeBeatha436! Please add these properties to your `i` tag: 

```css
.btn i.fas {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-12px,-12px);
      line-height: 1.5rem;
      width: 23px;
}
```

Regards,
Dragos
